#!/bin/bash

[ $# -eq 0 ] && { echo -e "Please supply input text.\nUsage: $0 input_text output_file[optional]"; exit 1; }

input="$1"
# for i in "$@"; do $input+=$i; done
# echo "$input"
# args=("$@")
# i = ${#args[*]}
#items=($args[@])
#echo "${items[1]}"

# input="${args[$((1))]}"
# output="${args[$((2))]}"
output="$2"

# [[ -z "$output" ]] && output_file="out" || output_file="$output"

./scripts/generate_scm "$input" "$output"
padsp $ESTDIR/../festival/bin/festival festvox/ku_ne_nab_clunits.scm -b "input.scm" && echo "Wave generated in out.wav file"
