#!/bin/sh

[ $# -eq 0 ] && { echo -e "Please supply input text.\nUsage: $0 input_text output_file[option]"; exit 1; }

input="$1"
# output=$2
cd scripts
transliterated=$(python3 run_trans.py "$input")

cd ..
# [[ -z "$output" ]] && output_file="out" || output_file="$output"

./scripts/generate_scm "$transliterated" "out"
padsp $ESTDIR/../festival/bin/festival festvox/ku_ne_nab_clunits.scm -b "input.scm" && echo "Wave generated in out.wav file"

cvlc out.wav &
